export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)' }
];
export const APP_FEATURES = [
    {
        id: 1,
        title: "Tailored just for you",
        description: "get interview questions and model answers based on your role, experience, and specific focus areas.",
    },
    {
        id: 2,
        title: "Learn at your own pace",
        description: "Expand answers only when you're ready. Dive deeper into concepts  instantly with AI-generated  details explanations.",
    },
    {
        id: 3,
        title: "capture your Insights",
        description: "Add personal notes to any question and pin important ones  to the top-making your learning more organized and effective.",
    },
    {
        id: 4,
        title: 'Understand the "why" behind answers',
        description: "Beyond just answers-unlock the detailed  concepts explanations generated by AI,helping you truly master each topic.",
    },
    {
        id: 5,
        title: "Save,organize,and revisit",
        description: "easily save interview sets,organize them nearly, and pick up right where you left off,ensuring a seamless learning experience.",

    }
];